name: ahziyah_flutter
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  dio_smart_retry: ^5.0.0
  dotted_border: ^2.1.0
  easy_paymob: ^0.0.1
  email_validator: ^3.0.0
  file_picker: ^8.3.1
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.1
  flutter:
    sdk: flutter

  flutter_local_notifications: ^18.0.1
  # flutter_secure_storage: ^4.2.0
  flutter_svg: ^2.0.17
  get: ^4.6.6
  hive_ce: ^2.10.0
  hive_ce_flutter: ^2.2.0
  image_picker: ^1.1.2
  package_info_plus: ^8.2.0
  path: ^1.9.0
  pretty_dio_logger: ^1.3.1
  pretty_logger: ^1.0.0
  uuid: ^4.5.1
  visibility_detector: ^0.4.0+2
  crystal_navigation_bar: ^1.0.2
  iconly: ^1.0.1
  animations: ^2.0.11
  flutter_rating_bar: ^4.0.1
  intl: ^0.20.2
  animate_do: ^3.3.8
  url_launcher: ^6.3.1
dev_dependencies:
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_ce_generator: ^1.8.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/images/about/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
